# 5/4
# Generated by Django 5.1.5 on 2025-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
    ]
